name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
# ==================================================
# Windows + Linux Build
# ==================================================
  build-linux-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup WSL
      run: |
        wsl --install -d Ubuntu-22.04 || true
    - name: Build
      shell: pwsh
      run: |
        $version="${{github.ref_name}}".Replace("v","")
        .\make_release.ps1 -Version $version
    - name: Upload Windows Linux
      uses: actions/upload-artifact@v4
      with:
        name: win-linux
        path: |
          publish/*.zip
          publish/*.tar.gz
# ==================================================
# macOS
# ==================================================
  build-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build macOS
      shell: bash
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        chmod +x PackageMacApp.sh
        ./PackageMacApp.sh $VERSION
    - name: Create DMG
      shell: bash
      run: |
        brew install create-dmg
        VERSION=${GITHUB_REF_NAME#v}
        create-dmg \
        --volname "PDFMerger $VERSION" \
        --window-size 600 400 \
        --icon "PDFMerger.app" 150 150 \
        PDFMerger.$VERSION.dmg \
        PDFMerger.app
    - uses: actions/upload-artifact@v4
      with:
        name: macos
        path:
          |
          *.dmg
# ==================================================
# Create Release
# ==================================================
  release:
    needs:
      - build-linux-windows
      - build-macos
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/**/*.zip
          artifacts/**/*.tar.gz
          artifacts/**/*.dmg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
